name: qlora
channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.2=pyhc872135_1
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - accelerate==0.34.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.4.0
      - bitsandbytes==0.43.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - datasets==2.18.0
      - deprecated==1.3.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2024.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.3
      - modelscope==1.31.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - networkx==3.5
      - neural-compressor==3.5
      - numpy==1.26.4
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prettytable==3.16.0
      - propcache==0.4.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyarrow-hotfix==0.7
      - pycocotools==2.0.10
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - schema==0.7.8
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentry-sdk==2.43.0
      - setproctitle==1.3.7
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.9.1+cu128
      - torchvision==0.24.1+cu128
      - tqdm==4.67.1
      - transformers==4.50.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.17.8
      - wcwidth==0.2.14
      - wrapt==2.0.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\Administrator\anaconda3\envs\qlora
